### ISSUE TITLE
Holograms 240 Placement

### ISSUE THREAD

**Issue by dtmnash** [Microsoft/HolographicAcademy#1]
If you follow the instructions things stop working on holograms 240 once you hit Chapter 3 Shared Coordinates. 

The behavior I'm seeing is that the hologram can no longer be placed in the scene and when using two HoloLenses they do no actually have a shared view of the EnergyHub

**Comment by NeerajW** [comment]
@dtmnash thank you for the post but this sounds like an issue in your project. The right place for us to help debug this is on the forums: https://forums.hololens.com/categories/questions-and-answers. 
Please follow up with questions and more specifics there and we can help triage your issue. Thank you!
