### ISSUE TITLE
Holograms-101 - need to stop playing the rolling sound on reset

### ISSUE THREAD

**Issue by timGerken** [Microsoft/HolographicAcademy#14]
1. In catchup-chapter 7, position the stage on the floor and drop a sphere.
2. Notice the sphere rolls off the stage and onto the floor.
3. If the spatial mapping mesh is noisy enough, it will continue to roll with enough velocity to keep the rolling sound playing
4. Issue the "reset world" command
5. Notice, the sphere goes back to its original local position, but the rolling wave is still playing.

**Comment by keveleigh** [comment]
Closed via #40
