### ISSUE TITLE
Selecting the Energy hub does not work in chapter 3

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/HolographicAcademy#15]
https://github.com/Microsoft/HolographicAcademy/tree/Holograms-240-SharedHolograms/Catchup-Chapters/3-SharedCoordinates . Selecting the Energy hub does not work . Cause: GestureManager sends OnSelect but active object is _Base_, not the root object, so OnSelect on HologramPlacement is never called. Simplest (but rather crude ) fix is to change in GestureManager  
focusedObject.SendMessage("OnSelect"); 
to
focusedObject.SendMessageUpwards("OnSelect");

**Comment by NeerajW** [comment]
That chapter does not let you place the EnergyHub until the anchor has been established.
So till the ImportExportAnchorManager is done creating and exporting and anchor you will not be able to place your energy hub.

Have you ensured the anchor got established?

**Comment by keveleigh** [comment]
Unable to repro. Please reopen if you're still seeing this.

**Comment by hanfengsunshine** [comment]
> That chapter does not let you place the EnergyHub until the anchor has been established.
> So till the ImportExportAnchorManager is done creating and exporting and anchor you will not be able to place your energy hub.
> 
> Have you ensured the anchor got established?

Hey, it says wait around 1 min to create anchor, but on my side nothing appear.
