### ISSUE TITLE
Rename HoloToolkit folders and namespace for Academy content

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/HolographicAcademy#16]
We want to make it easier for developers to use the latest HoloToolkit from GitHub if they are starting from an Academy course.

To avoid merge conflicts and not incurring the tax of always keep teachable content in sync with GitHub, we can do the following things:
1. Rename HoloToolkit folder under Assets to something like HoloToolkit-Academy-CourseNumber
2. Rename the namespace HoloToolkit.Unity to something like Academy.HoloToolkit.Unity

**Comment by angelaHillier** [comment]
Spatial Mapping was updated to use a custom HoloToolkit with commit fc38186.

**Comment by angelaHillier** [comment]
This is now done for Holograms 240 as well. HoloToolkit was renamed to 'HoloToolkit-Sharing-240' and namespaces were changed to Academy.HoloToolkit.Unity and Academy.HoloToolkit.Sharing.
commit d5be86a and commit 71317b3

**Comment by keveleigh** [comment]
And done for Holograms 220, thanks to @davidkline-ms! Closing this Issue.
