### ISSUE TITLE
Holograms 240: Remove catch-up chapters

### ISSUE THREAD

**Issue by angelaHillier** [Microsoft/HolographicAcademy#26]
Rename the catch-up chapter '7-Finale' to 'Completed' and then remove all other catch-up chapters from this course. Catch-up chapters were useful for Build, but no longer necessary. They are too costly to maintain and makes the download size for the class significantly larger.

**Comment by angelaHillier** [comment]
Done!

**Comment by hanfengsunshine** [comment]
Hey, however when I deploy this Completed Code, when I click 1 ploy, and wait then nothing happens, do you know why? Thank you!

**Comment by keveleigh** [comment]
>when I click 1 ploy

What is this referring to?
