### ISSUE TITLE
SpatialMapping - 230: Utilities Prefab Main Camera 

### ISSUE THREAD

**Issue by lukaswerz** [Microsoft/HolographicAcademy#28]
Hello

The SpatialMapping - 230: Utilities Prefab Main Camera is not a valid Unity object and can't be added to the Hierarchy anymore.

(Unity HoloLens 5.4.0f3-HTP (64-bit))

**Comment by angelaHillier** [comment]
Thanks for reporting this issue! I'll fix it soon.
We are in the process of updating all of our Academy courses to use the latest version of Unity (5.5.0f3), so there is a good chance that they will no longer work with 5.4 after updates.

**Comment by lukaswerz** [comment]
Wow! Thanks for this quick answer, I did not expect an answer so fast.
I will update to 5.5.0f3.
Thanks a lot.

**Comment by lukaswerz** [comment]
Works with  Unity 5.5.0f3. I close the issue. Thanks for the help

**Comment by angelaHillier** [comment]
Thanks!
