### ISSUE TITLE
[Holograms 101]Error SendMessageUpwards has no receiver

### ISSUE THREAD

**Issue by MaximeGL** [Microsoft/HolographicAcademy#37]
Hello,

**Context:** 

Holograms 101
When I tap on a spatial mesh I have this error: "SendMessageUpwards has no receiver" 
This error appear only when I use Holographic Remoting Player for streaming my application via Unity (not with debug or release version).

**Suggested solution:**

Add l.25 in GazeGestureManager.cs the option DontRequireReceiver to SendMessageUpwards()
`FocusedObject.SendMessageUpwards("OnSelect", SendMessageOptions.DontRequireReceiver);`

I think we can have the same problem when we use SendMessage() without option

Maxime

**Comment by keveleigh** [comment]
Fixed via 78342ba4182415e97aad6b22a42a951bb28d7d32. Thanks for the suggestion!
