### ISSUE TITLE
Update Academy Documentation link

### ISSUE THREAD

**Issue by KurtRMueller** [Microsoft/HolographicAcademy#38]
Currently, the repo points to a broken link: https://developer.microsoft.com/en-us/windows/holographic/academy. 

It should point to: https://developer.microsoft.com/en-us/windows/mixed-reality/academy.

Given the name change, maybe this repo should move as well? Obviously, that's up to you all though.

**Comment by sorianog** [comment]
Looks like the change has been made. Works for me now (on mobile).
