### ISSUE TITLE
HoloToolkit link from the Camera in Unity article goes to a 404 page

### ISSUE THREAD

**Issue by superlime** [Microsoft/HolographicAcademy#4]
The link at the very bottom of the [Camera in Unity](https://developer.microsoft.com/en-us/windows/holographic/Camera_in_Unity.html) article in the "See also" section, linking to [HoloToolkit Main Camera.prefab](https://github.com/Microsoft/HoloToolkit-Unity/tree/master/Assets/HoloToolkit/Prefabs/Camera) doesn't appear to exist in the repo.  Maybe it was supposed to link to [Main Camera.prefab](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Prefabs/Main%20Camera.prefab)?

**Comment by NeerajW** [comment]
@superlime thanks for logging this issue. It has been fixed in our documentation internally but has not made it's way to the public source. I will keep this issue open until it does.

**Comment by NeerajW** [comment]
Live docs have been updated with the fix. Closing this issue.
