### ISSUE TITLE
Academy needs to be updated to Unity 2017.2

### ISSUE THREAD

**Issue by asterikx** [Microsoft/HolographicAcademy#42]
Hi,

I'm getting the error 

`Assets\Holograms\Support\Fitbox\Fitbox.cs(43,46): error CS0246: The type or namespace name 'GestureRecognizer' could not be found (are you missing a using directive or an assembly reference?)`

Moreover I'm getting the warning

`Assets\Holograms\Support\Fitbox\Fitbox.cs(44,9): warning CS0618: 'GestureRecognizer.TappedEvent' i obsolete: 'TappedEvent is deprecated, and will be removed in a future release. Use OnTappedEvent instead'`

I looks like some APIs have changed, and that some of the other tutorials might also be affected.

I'm using Unity version 2017.2.0f3 and Visual Studio 2017 (version 15.4.1).

**Comment by keveleigh** [comment]
Looks like my updates to the courses weren't pushed properly! I'll get these fixed up ASAP. Thanks for bringing this to my attention!

**Comment by keveleigh** [comment]
The code has been updated for 101, but the docs will likely be out of sync for a bit. I'll leave this issue open until all courses and docs are published.

**Comment by asterikx** [comment]
Thanks a lot!

**Comment by Valkyrie-MT** [comment]
Thanks for updating 101.  That is a great start to help me see what needs to change in Unity 2017.2.  Do you know when the Shared Holograms example might get updated?

**Comment by keveleigh** [comment]
Apologies for the delay, but Shared Holograms is now updated! Closing the issue.
