### ISSUE TITLE
unity projects can't be built when I put Holotoolkit in github and academy code together

### ISSUE THREAD

**Issue by jomainqaq** [Microsoft/HolographicAcademy#47]
When I import the resources on GitHub and the resources in the college into a scenario，Although there is a lot of bug but I can click play。But when I want to build it ,there is something wrong.

`Plugin 'PlaneFinding.dll' is used from several locations:
 Assets/HoloToolkit/SpatialMapping/Plugins/WSA/x64/PlaneFinding.dll would be copied to <PluginPath>/Plugins/X64/PlaneFinding.dll
 Assets/HoloToolkit-SpatialMapping-230/SpatialMapping/Plugins/WSA/x64/PlaneFinding.dll would be copied to <PluginPath>/Plugins/X64/PlaneFinding.dll
Plugin 'PlaneFinding.dll' is used from several locations:
 Assets/HoloToolkit-SpatialMapping-230/SpatialMapping/Plugins/WSA/x86/PlaneFinding.dll would be copied to <PluginPath>/Plugins/X86/PlaneFinding.dll
 Assets/HoloToolkit/SpatialMapping/Plugins/WSA/x86/PlaneFinding.dll would be copied to <PluginPath>/Plugins/X86/PlaneFinding.dll
Please fix plugin settings and try again.

UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at C:/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`
`Plugins colliding with each other.`
`Build completed with a result of 'Failed'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`
`UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x0020e] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:181 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00065] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:88 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

As a beginner, this problem has troubled me for a long time，I do not know if there is a solution，thank you。

**Comment by keveleigh** [comment]
This is true. The Toolkit folders in the Academy courses hadn't been updated in a long time. Now, 210, 211, and 212 have been updated to a very recent Toolkit release, and the other courses will be updated soon.

As a note, to update any Toolkit versions, you should delete the existing Toolkit and update to an entirely new folder. This prevents collisions, like you were seeing, if files have been moved between releases.
