### ISSUE TITLE
Link in Holograms 100 describing clipping plane in more detail doesn't go to the correct section of the article

### ISSUE THREAD

**Issue by superlime** [Microsoft/HolographicAcademy#5]
The link in the [Holograms 100](https://developer.microsoft.com/en-us/windows/holographic/holograms_100) course giving more detail about the [HoloLens recommended](https://developer.microsoft.com/en-us/windows/holographic/Camera_in_Unity.html#Clip_Planes) distance for the clip plane, ends up going to the top of the page rather than the div for the [Clip planes](https://developer.microsoft.com/en-us/windows/holographic/Camera_in_Unity.html#Clip_planes) because the "p" in planes is lowercase on the actual page (the link uses a capital P).

**Comment by NeerajW** [comment]
@superlime keep eye :) Thank you so much. Checked in the fix to our documentation. Will keep this open till it shows up on the live page.

**Comment by NeerajW** [comment]
Live docs have been updated with the fix. Closing issue.
