### ISSUE TITLE
Unity 2019 occurs error after importing the package

### ISSUE THREAD

**Issue by USTBVEO** [microsoft/HolographicAcademy#62]
Assets\HoloToolkit\BuildAndDeploy\Editor\BuildSLNUtilities.cs(110,75): error CS0117: 'EditorUserBuildSettings' does not contain a definition for 'wsaGenerateReferenceProjects'

**Comment by keveleigh** [comment]
We haven't been keeping these samples up to date with new Unity versions. I believe the newest version we've tested with is 2017.

**Comment by USTBVEO** [comment]
您发给我的信件已收到。from Wei Yang/杨威
 
   This is an automatic reply, confirming that your e-mail was received.Thank you
